// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvGC7AcGYrIfpIdx5KZrob0Bum7zAVsM',
    appId: '1:353042503516:web:5706d964c72f1f6eb5d399',
    messagingSenderId: '353042503516',
    projectId: 'gestionticket-9d01f',
    authDomain: 'gestionticket-9d01f.firebaseapp.com',
    storageBucket: 'gestionticket-9d01f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYIRDn-5yGZr23qx7k6Q4r53E8u3vqrjo',
    appId: '1:353042503516:android:4a9a17a084b33a73b5d399',
    messagingSenderId: '353042503516',
    projectId: 'gestionticket-9d01f',
    storageBucket: 'gestionticket-9d01f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJ5l8Qub2yXP8OFhR91974GnV7lgDfHo',
    appId: '1:353042503516:ios:5cad416762bdcdaab5d399',
    messagingSenderId: '353042503516',
    projectId: 'gestionticket-9d01f',
    storageBucket: 'gestionticket-9d01f.appspot.com',
    iosBundleId: 'com.example.gestionTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJ5l8Qub2yXP8OFhR91974GnV7lgDfHo',
    appId: '1:353042503516:ios:5cad416762bdcdaab5d399',
    messagingSenderId: '353042503516',
    projectId: 'gestionticket-9d01f',
    storageBucket: 'gestionticket-9d01f.appspot.com',
    iosBundleId: 'com.example.gestionTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvGC7AcGYrIfpIdx5KZrob0Bum7zAVsM',
    appId: '1:353042503516:web:bd3672d3fcf68431b5d399',
    messagingSenderId: '353042503516',
    projectId: 'gestionticket-9d01f',
    authDomain: 'gestionticket-9d01f.firebaseapp.com',
    storageBucket: 'gestionticket-9d01f.appspot.com',
  );
}
